/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissaoRouteImport } from './routes/missao'
import { Route as ProjetoIntegradorRouteImport } from './routes/projeto-integrador'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ValoresRouteImport } from './routes/valores'
import { Route as VisaoRouteImport } from './routes/visao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoRoute = MissaoRouteImport.update({
  id: '/missao',
  path: '/missao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoIntegradorRoute = ProjetoIntegradorRouteImport.update({
  id: '/projeto-integrador',
  path: '/projeto-integrador',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ValoresRoute = ValoresRouteImport.update({
  id: '/valores',
  path: '/valores',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaoRoute = VisaoRouteImport.update({
  id: '/visao',
  path: '/visao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/missao': typeof MissaoRoute
  '/projeto-integrador': typeof ProjetoIntegradorRoute
  '/quem-somos': typeof QuemSomosRoute
  '/valores': typeof ValoresRoute
  '/visao': typeof VisaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/missao': typeof MissaoRoute
  '/projeto-integrador': typeof ProjetoIntegradorRoute
  '/quem-somos': typeof QuemSomosRoute
  '/valores': typeof ValoresRoute
  '/visao': typeof VisaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/missao': typeof MissaoRoute
  '/projeto-integrador': typeof ProjetoIntegradorRoute
  '/quem-somos': typeof QuemSomosRoute
  '/valores': typeof ValoresRoute
  '/visao': typeof VisaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/missao'
    | '/projeto-integrador'
    | '/quem-somos'
    | '/valores'
    | '/visao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/missao'
    | '/projeto-integrador'
    | '/quem-somos'
    | '/valores'
    | '/visao'
  id:
    | '__root__'
    | '/'
    | '/missao'
    | '/projeto-integrador'
    | '/quem-somos'
    | '/valores'
    | '/visao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MissaoRoute: typeof MissaoRoute
  ProjetoIntegradorRoute: typeof ProjetoIntegradorRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ValoresRoute: typeof ValoresRoute
  VisaoRoute: typeof VisaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao': {
      id: '/missao'
      path: '/missao'
      fullPath: '/missao'
      preLoaderRoute: typeof MissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-integrador': {
      id: '/projeto-integrador'
      path: '/projeto-integrador'
      fullPath: '/projeto-integrador'
      preLoaderRoute: typeof ProjetoIntegradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valores': {
      id: '/valores'
      path: '/valores'
      fullPath: '/valores'
      preLoaderRoute: typeof ValoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visao': {
      id: '/visao'
      path: '/visao'
      fullPath: '/visao'
      preLoaderRoute: typeof VisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MissaoRoute: MissaoRoute,
  ProjetoIntegradorRoute: ProjetoIntegradorRoute,
  QuemSomosRoute: QuemSomosRoute,
  ValoresRoute: ValoresRoute,
  VisaoRoute: VisaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
